export const errorCode = {
    ADMIN_ONLY_ACCESS: 'ADMIN_ONLY_ACCESS',
    EXCEEDED_ALLOWED_DECIMAL_PLACES_FOR_PRICE_ERROR:
        'EXCEEDED_ALLOWED_DECIMAL_PLACES_FOR_PRICE_ERROR',
    EXCEEDED_ALLOWED_DECIMAL_PLACES_FOR_VOLUME_ERROR:
        'EXCEEDED_ALLOWED_DECIMAL_PLACES_FOR_VOLUME_ERROR',
    UNABLE_TO_UPDATE_DUE_TO_END_TIME_BUFFER_ERROR:
        'UNABLE_TO_UPDATE_DUE_TO_END_TIME_BUFFER_ERROR',
    UNABLE_TO_UPDATE_DUE_TO_START_TIME_BUFFER_ERROR:
        'UNABLE_TO_UPDATE_DUE_TO_START_TIME_BUFFER_ERROR',
    UNABLE_TO_UPDATE_AUCTION_INTERVAL: 'UNABLE_TO_UPDATE_AUCTION_INTERVAL',
    AUCTION_CANCEL_ACCESS_DENIED: 'AUCTION_CANCEL_ACCESS_DENIED',
    PRIORITY_DOES_NOT_EXIST_ERROR: 'PRIORITY_DOES_NOT_EXIST_ERROR',
    SECTOR_DOES_NOT_EXISTS_ERROR: 'SECTOR_DOES_NOT_EXISTS_ERROR',
    SECTOR_ALREADY_EXISTS_ERROR: 'SECTOR_ALREADY_EXISTS_ERROR',
    PRIORITY_ALREADY_EXIST_ERROR: 'PRIORITY_ALREADY_EXIST_ERROR',
    CONFLICT: 'CONFLICT',
    DEFAULT_ERROR: 'IGX_DEFAULT_ERROR',
    CUSTOM_COMMON_ERROR: 'IGX_CUSTOM_COMMON_ERROR',
    DATA_VALIDATION_ERROR: 'IGX_DATA_VALIDATION_ERROR',
    NOT_ALLOWED_TO_VIEW_THIS_INFO_ERROR: 'NOT_ALLOWED_TO_VIEW_THIS_INFO_ERROR',
    AUTHORIZATION_ERROR: 'AUTH_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    NOT_FOUND: 'NOT FOUND',
    AUTH_INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN_ERROR',
    AUTH_INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN_ERROR',
    RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED_ERROR',
    RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID_ERROR',
    AUTH_ACCESS_TOKEN_EXPIRE: 'AUTH_ACCESS_TOKEN_EXPIRE_ERROR',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD_ERROR',
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST_ERROR',
    USER_ALREADY_LOGGED_IN: 'USER_ALREADY_LOGGED_IN',
    USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST_ERROR',
    COMPANY_ALREADY_EXIST: 'COMPANY_ALREADY_EXIST',
    COMPANY_DOES_NOT_EXIST: 'COMPANY_DOES_NOT_EXIST',
    AUCTION_ALREADY_EXIST: 'AUCTION_ALREADY_EXIST',
    AUCTION_DOES_NOT_EXIST: 'AUCTION_DOES_NOT_EXIST',
    AUCTION_ALREADY_PUBLISHED: 'AUCTION_ALREADY_PUBLISHED',
    INVALID_STATE_FOR_BIDDER_ALLOCATION: 'INVALID_STATE_FOR_BIDDER_ALLOCATION',
    INVALID_BIDDER_VOLUME: 'INVALID_BIDDER_VOLUME',
    OTP_TOKEN_INVALID: 'OTP_TOKEN_INVALID',
    INCORRECT_OTP: 'INCORRECT_OTP',
    OLD_PASSWORD: 'OLD_PASSWORD',
    TOKEN_NOT_AVAILABLE: 'TOKEN_NOT_AVAILABLE',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    INVALID_USER: 'INVALID_USER',
    USER_ID_LOCKED: 'USER_ID_LOCKED',
    RESET_PASSWORD_REQUIRED: 'RESET_PASSWORD_REQUIRED',
    INVALID_CONFIG_ID: 'INVALID_CONFIG_ID',
    USER_SUSPENDED: 'USER_SUSPENDED',
    USER_INACTIVE: 'USER_INACTIVE',
    COMPANY_SUSPENDED: 'COMPANY_SUSPENDED',
    COMPANY_INACTIVE: 'COMPANY_INACTIVE',

    // CLient
    INVALID_CLIENT_ID: 'INVALID_CLIENT_ID',
    INACTIVE_CLIENT: 'INACTIVE_CLIENT',

    WORKSPACE_ALREADY_EXIST: 'WORKSPACE_ALREADY_EXIST',
    WORKSPACE_DOES_NOT_EXIST: 'WORKSPACE_DOES_NOT_EXIST',
    NO_ACCESS_TO_WORKSPACE: 'NO_ACCESS_TO_WORKSPACE',
    DEFAULT_WORKSPACE_CANT_DELETE: 'DEFAULT_WORKSPACE_CANT_DELETE',
    INACTIVE_OR_SUSPENDED_USER: 'INACTIVE_OR_SUSPENDED_USER',
    NO_ID_IN_PARAMS: 'NO_ID_IN_PARAMS',

    // Market Error Code
    INVALID_SEGMENT: 'IGX_INVALID_SEGMENT',
    INVALID_INSTRUMENT: 'INVALID_INSTRUMENT',

    // ORDER
    INVALID_ORDER: 'INVALID_ORDER',
    INVALID_ORDER_ID: 'INVALID_ORDER_ID',
    ORDER_FILE_NOT_FOUND: 'ORDER_FILE_NOT_FOUND',
    INVALID_ORDER_FILE: 'INVALID_ORDER_FILE',

    //Master
    CONFIGURATION_ALREADY_EXIST: 'CONFIGURATION_ALREADY_EXIST',
    CONFIGURATION_DOES_NOT_EXIST: 'CONFIGURATION_DOES_NOT_EXIST',
    SYSTEM_CONFIG_CAN_NOT_BE_ADDED: 'SYSTEM_CONFIG_CAN_NOT_BE_ADDED',
    SYSTEM_CONFIG_CAN_NOT_BE_UPDATED: 'SYSTEM_CONFIG_CAN_NOT_BE_UPDATED',

    //Bid
    NOT_A_BETTER_BID: 'NOT_A_BETTER_BID',
    SAME_BID_ALREADY_EXIST: 'SAME_BID_ALREADY_EXIST',
    BID_ALREADY_EXIST: 'BID_ALREADY_EXIST',
    NO_BID_EXIST: 'NO_BID_EXIST',
    MAXIMUM_VOLUME_ALLOWED_LIMIT_EXCEEDS:
        'MAXIMUM_VOLUME_ALLOWED_LIMIT_EXCEEDS',
    MINIMUM_VOLUME_ALLOWED_LIMIT_EXCEEDS:
        'MINIMUM_VOLUME_ALLOWED_LIMIT_EXCEEDS',
    MAXIMUM_PRICE_ALLOWED_LIMIT_EXCEEDS: 'MAXIMUM_PRICE_ALLOWED_LIMIT_EXCEEDS',
    MINIMUM_PRICE_ALLOWED_LIMIT_EXCEEDS: 'MINIMUM_PRICE_ALLOWED_LIMIT_EXCEEDS',
    MAXIMUM_TENURE_ALLOWED_LIMIT_EXCEEDS:
        'MAXIMUM_TENURE_ALLOWED_LIMIT_EXCEEDS',
    MINIMUM_TENURE_ALLOWED_LIMIT_EXCEEDS:
        'MINIMUM_TENURE_ALLOWED_LIMIT_EXCEEDS',
    NOT_ALLOWED_TO_PLACE_BID: 'NOT_ALLOWED_TO_PLACE_BID',
    CAN_NOT_PLACE_BID: 'CAN_NOT_PLACE_BID',
    CAN_NOT_PLACE_BID_IN_BID_PHASE_WITHOUT_BID_IN_IPO:
        'CAN_NOT_PLACE_BID_IN_BID_PHASE_WITHOUT_BID_IN_IPO',
    CAN_NOT_PLACE_BID_IN_YOUR_OWN_AUCTION:
        'CAN_NOT_PLACE_BID_IN_YOUR_OWN_AUCTION',
    CAN_NOT_PLACE_MORE_THAN_ONE_BID_IN_IPO:
        'CAN_NOT_PLACE_MORE_THAN_ONE_BID_IN_IPO',
    MIN_PRICE_TICK_SIZE: 'MIN_PRICE_TICK_SIZE',
    MIN_VOLUME_TICK_SIZE: 'MIN_VOLUME_TICK_SIZE',
    MIN_TENURE_TICK_SIZE: 'MIN_TENURE_TICK_SIZE',
    FILE_NOT_FOUND_ERROR: 'FILE_NOT_FOUND_ERROR',
    FILE_BUFFER_ERROR: 'FILE_BUFFER_ERROR',
    IMAGE_NOT_FOUND_ERROR: 'IMAGE_NOT_FOUND_ERROR',
    DOG_IMAGE_NOT_FOUND_ERROR: 'DOG_IMAGE_NOT_FOUND_ERROR',
    NOT_VALID_IMAGE_FILE_ERROR: 'NOT_VALID_IMAGE_FILE_ERROR',
    COMPRESSION_FAILED_ERROR: 'COMPRESSION_FAILED_ERROR',
    FILE_DELETION_ERROR: 'FILE_DELETION_ERROR',
};
